export const categories = [
  { id: 1, name: "Income Tax Litigation", experts: 10 },
  { id: 2, name: "Import Export Code", experts: 9 },
  { id: 3, name: "TDS / TCS Compliance", experts: 5 },
  { id: 4, name: "Finance", experts: 5 },
  { id: 5, name: "Financial Planning", experts: 4 },
  { id: 6, name: "FSSAI", experts: 4 },
  { id: 7, name: "Company Law", experts: 6 },
  { id: 8, name: "ROC Filings", experts: 7 },
  { id: 9, name: "GST Litigation", experts: 21 },
  { id: 10, name: "Accounting", experts: 19 },
  { id: 11, name: "GST Registration", experts: 18 },
  { id: 12, name: "Income Tax Return", experts: 17 },

  { id: 13, name: "GST Returns", experts: 15 },
  { id: 14, name: "Capital Gains", experts: 12 },
  { id: 15, name: "Tax Refunds", experts: 11 },
  { id: 16, name: "Business Closure", experts: 8 },
  { id: 17, name: "Child Custody", experts: 6 },
  { id: 18, name: "Data Privacy", experts: 7 },
  { id: 19, name: "Hindu Marriage", experts: 9 },
  { id: 20, name: "Court Marriage", experts: 10 },

  { id: 21, name: "ROC Litigation", experts: 8 },
  { id: 22, name: "Startup Registration", experts: 14 },
  { id: 23, name: "Trademark Registration", experts: 13 },
  { id: 24, name: "Copyright Filing", experts: 9 },
  { id: 25, name: "Patent Filing", experts: 6 },
  { id: 26, name: "Legal Notice", experts: 11 },
  { id: 27, name: "Divorce Law", experts: 10 },
  { id: 28, name: "Property Law", experts: 12 },

  { id: 29, name: "Loan Consultation", experts: 7 },
  { id: 30, name: "Insurance Claims", experts: 9 },
  { id: 31, name: "Banking Issues", experts: 8 },
  { id: 32, name: "Cyber Crime", experts: 6 },
  { id: 33, name: "Consumer Court", experts: 7 },
  { id: 34, name: "Labour Law", experts: 10 },
  { id: 35, name: "NGO Registration", experts: 5 },
  { id: 36, name: "Society Registration", experts: 6 },

  { id: 37, name: "Import Export Compliance", experts: 9 },
  { id: 38, name: "GST Notice Reply", experts: 13 },
  { id: 39, name: "Tax Planning", experts: 14 },
  { id: 40, name: "Wealth Management", experts: 8 },

  { id: 41, name: "Business Setup", experts: 16 },
  { id: 42, name: "Partnership Firm", experts: 11 },
  { id: 43, name: "LLP Registration", experts: 12 },
  { id: 44, name: "Private Limited Company", experts: 15 },

  { id: 45, name: "ESI Registration", experts: 6 },
  { id: 46, name: "PF Registration", experts: 7 },
  { id: 47, name: "Payroll Management", experts: 9 },
  { id: 48, name: "Audit Services", experts: 10 },

  { id: 49, name: "Business Advisory", experts: 13 },
  { id: 50, name: "Legal Consultation", experts: 18 },
];